apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-shared.yaml
  - secrets.yaml
  - postgres.yaml
  - chromadb.yaml
  - gateway.yaml
  - workers.yaml
  - nats-stream.yaml
